# Generated by Django 2.2.12 on 2020-08-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20200816_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Dirección '),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electronico'),
        ),
    ]
